# Impede que os usu치rios criem issues sem usar um dos seus templates (Bug, Change Request, etc.)
blank_issues_enabled: false

# # Links 칰teis que aparecer칚o na tela de "New Issue" como alternativas
# contact_links:
#   - name: 游닄 Documenta칞칚o Interna
#     url: https://sua-org.atlassian.net/wiki/seu-projeto # Exemplo de link para Wiki/Confluence
#     about: Consulte as regras de neg칩cio e fluxos antes de abrir uma solicita칞칚o.

#   - name: 游댏 Guia de Seguran칞a & Autentica칞칚o
#     url: https://github.com/sua-org/.github/blob/main/SECURITY_GUIDELINES.md
#     about: Lembre-se que rotas protegidas exigem verifica칞칚o de login peri칩dica conforme o padr칚o da org.

#   - name: 游눫 Canal de Suporte (Slack/Teams)
#     url: https://slack.com/sua-org
#     about: Para d칰vidas r치pidas que n칚o necessitam de um ticket formal.
